In [3]:
import numpy as np
arr=np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [2]:
print(type(arr))

<class 'numpy.ndarray'>


In [5]:
arr1=np.array([[3],[4],[5]])
arr1

array([[3],
       [4],
       [5]])

In [7]:
arr2=np.zeros((3,4),dtype=int)
print(arr2)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [6]:
arr3=np.ones((3,4))
arr3

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [4]:
#creating an array with range of values
arr4=np.arange(0,10,2)
arr4

array([0, 2, 4, 6, 8])

In [5]:
print(arr4[3])

6


In [6]:
print(arr4[1:4])

[2 4 6]


In [8]:
#modify the values in the array
arr4[3]=10
arr4

array([ 0,  2,  4, 10,  8])

In [11]:
print(arr4.min())
print(arr4.max())
print(arr4.sum())
print(arr4.mean())

0
10
24
4.8


In [ ]:
#how to use pI value 
arr5=np.array([0,np.pi/2,np.pi])
print(np.sin(arr5))
print(np.cos(arr5))
print(np.log(arr5)) #logerthemic
print(np.exp(arr5)) #Exponent

In [4]:
#we can pass the data type of our wish
i=np.array([1,2,3,4],dtype=complex)
i

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j])

In [10]:
np.array([1,2,3,4],dtype=str)

array(['1', '2', '3', '4'], dtype='<U1')

In [16]:
a1=np.random.random((3,3))
a1=np.round(a1*100)
print(a1)
print(np.max(a1,axis=1))
print(np.prod(a1,axis=1))


[[76. 10.  4.]
 [38. 65.  9.]
 [71.  6. 84.]]
[76. 65. 84.]
[ 3040. 22230. 35784.]


In [24]:
#mean/median/std/var
np.mean(a1,axis=1)
np.median(a1,axis=1)
np.std(a1,axis=1)
np.var(a1,axis=1)

array([1064.        ,  522.88888889, 1164.22222222])

In [37]:
#dot functions 3X4 4X3=3X3
#in the above calculations 4 and 4 should be same
np.dot(a1,arr2)

In [36]:
#round /floor/ceil
print(np.ceil(np.random.random((3,4))*100))
print(np.round(np.random.random((3,4))*100))

[[75. 66. 60.  6.]
 [13. 67. 92. 57.]
 [15. 13.  4. 94.]]
[[18. 64. 29. 92.]
 [93. 75. 42. 55.]
 [67.  4. 13. 89.]]
