In [43]:
import numpy as np


In [25]:
#reshape
np.arange(1,13).reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [37]:

np.ones((3,4),dtype=str)

array([['1', '1', '1', '1'],
       ['1', '1', '1', '1'],
       ['1', '1', '1', '1']], dtype='<U1')

In [32]:
#use of random 
#it will generate the random values in the array in between o to 1
arr2=np.random.random((3,4))
arr2

array([[0.46481122, 0.48900258, 0.49643511, 0.51443427],
       [0.86199939, 0.74278963, 0.17041509, 0.80199396],
       [0.53538914, 0.444298  , 0.85786973, 0.79333139]])

In [40]:
#np.linspace (linear space)  
#it will create an array of list of elements in the given range from -10 to 10 
#where we have to generate 10 elemnts with equal disctance between th value ()
np.linspace(-10,10,10) #dtype=int

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [35]:
#indentity matrix is where diagonal elements are 1 rest of the elements are 0
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [44]:
np.arange(16).reshape(2,2,2,2)  #2*2*2*2

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])