In [1]:
import numpy as  np
a1=np.arange(12).reshape(3,4)
a2=np.arange(12,24).reshape(3,4)

In [10]:
#arthemetic operation
print(a1*2)
print(":--------------------------------------")
print(a2+3)
print(":--------------------------------------")
print(a2**3)
print(":--------------------------------------")

[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]
:--------------------------------------
[[15 16 17 18]
 [19 20 21 22]
 [23 24 25 26]]
:--------------------------------------
[[ 1728  2197  2744  3375]
 [ 4096  4913  5832  6859]
 [ 8000  9261 10648 12167]]


In [11]:
#Relational operation
print(a1>2)
print(":--------------------------------------")
print(a2<3)
print(":--------------------------------------")
print(a2==3)

[[False False False  True]
 [ True  True  True  True]
 [ True  True  True  True]]
:--------------------------------------
[[False False False False]
 [False False False False]
 [False False False False]]
:--------------------------------------
[[False False False False]
 [False False False False]
 [False False False False]]


In [12]:
#vectore operations
#for performing vector operations we make sure that the two vectors are same in size
print(a1**a2)
print(":--------------------------------------")
print(a1/a2)
print(":--------------------------------------")
print(a2-a1)

[[                   0                    1                16384
              14348907]
 [          4294967296         762939453125      101559956668416
     11398895185373143]
 [ 1152921504606846976 -1261475310744950487  1864712049423024128
   6839173302027254275]]
:--------------------------------------
[[0.         0.07692308 0.14285714 0.2       ]
 [0.25       0.29411765 0.33333333 0.36842105]
 [0.4        0.42857143 0.45454545 0.47826087]]
:--------------------------------------
[[12 12 12 12]
 [12 12 12 12]
 [12 12 12 12]]
