In [2]:
import numpy as np
H=np.arange(10)
A=np.arange(0,12).reshape(3,4)
R=np.arange(8).reshape(2,2,2)
print(H)
print("___________________________________________")
print(A)
print("___________________________________________")
print(R)

[0 1 2 3 4 5 6 7 8 9]
___________________________________________
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
___________________________________________
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [3]:
H[-1]

9

In [18]:
print(A[1][2])
print(H[0:7:2])
print(A[1,2])
print(R[1][0][1])

6
[0 2 4 6]
6
5


In [14]:
#to print the particular row
#to print the particular column
print(A[0,:])
print(A[:,2])
print(A[0:2,2])

[0 1 2 3]
[ 2  6 10]
[2 6]


In [30]:
A=np.arange(0,12).reshape(3,4)
print(A)
print("-----------------------------------")
print(A[::2])
print("-----------------------------------")
print(A[::2,::3])
print("-----------------------------------")
print(A[::2,1::2])
print("-----------------------------------")
print(A[1::2,0::3])
print("-----------------------------------")
print(A[0:2,1:4])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
-----------------------------------
[[ 0  1  2  3]
 [ 8  9 10 11]]
-----------------------------------
[[ 0  3]
 [ 8 11]]
-----------------------------------
[[ 1  3]
 [ 9 11]]
-----------------------------------
[[4 7]]
-----------------------------------
[[1 2 3]
 [5 6 7]]


In [33]:
arr1=np.arange(27).reshape(3,3,3)
arr1

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [40]:
for i in arr1:
    print(i)
#to iterate each and evry element in the array we use nditer
#nditer is a function which converts any dimensional array into single dimension
for i in  np.nditer(arr1):
    print(i,end=' ')
    


[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]
0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 

In [39]:
#transpose converts 3X4=4X3
A=np.arange(0,12).reshape(3,4)
print(A)
print(np.transpose(A))
print(A.T)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [44]:
#horizantal Stacking
#for stakc the shape should be same 
a4=np.arange(12).reshape(3,4)
a5=np.arange(12,24).reshape(3,4)
print(np.hstack((a4,a5)))
print("___________________________________________")
print(np.hstack((a4,a5,a5)))
print("___________________________________________")
print(np.hstack((a5,a4,a5,a5)))
print("___________________________________________")


[[ 0  1  2  3 12 13 14 15]
 [ 4  5  6  7 16 17 18 19]
 [ 8  9 10 11 20 21 22 23]]
___________________________________________
[[ 0  1  2  3 12 13 14 15 12 13 14 15]
 [ 4  5  6  7 16 17 18 19 16 17 18 19]
 [ 8  9 10 11 20 21 22 23 20 21 22 23]]
___________________________________________
[[12 13 14 15  0  1  2  3 12 13 14 15 12 13 14 15]
 [16 17 18 19  4  5  6  7 16 17 18 19 16 17 18 19]
 [20 21 22 23  8  9 10 11 20 21 22 23 20 21 22 23]]
___________________________________________


In [45]:
#vertical Stacking
print(np.vstack((a4,a5)))
print("___________________________________________")
print(np.vstack((a4,a5,a5)))
print("___________________________________________")
print(np.stack((a5,a4,a5,a5)))
print("___________________________________________")

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
___________________________________________
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
___________________________________________
[[[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]

 [[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
___________________________________________


In [48]:
#horizantal Splitting
np.hsplit(a4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [49]:
#vertical Splitting
np.vsplit(a4,2)   #we can't split it,it will throw an error